### ISSUE TITLE
can't figure how to configure

### ISSUE THREAD

**Issue by publiCities** [kahagon/php-usb#1]
Sorry i'm a newbie in compilation...
Can't figure what i need to indicate as "--with-usb" directory parameter. 
So i get this error:
"checking for usb in default path... configure: error: not found"

Could you please help ?

**Comment by oasynnoum** [comment]
Sorry for too late response.

I have changed config script to make more simplify.
--with-usb option has been abolished.
Basically, you can execute ./configure without any other options.
Please check out README.md for more detail.

**Comment by kahagon** [comment]
I've fixed configure script.
--with-usb option does not make sence anymore.

This option can receive argument 'yes' or 'no', and default is 'yes'.
'no' means 'does not configure to compile this ext'.

I mean this option has to ignored.

Regards,
