### ISSUE TITLE
Visual C++ Project file

### ISSUE THREAD

**Issue by kronika** [kahagon/php-usb#2]
Excellent extension, works like a charm on Linux, but I cant seem to open the project file to compile on windows, any advise - error states that the project file is corrupt.

**Comment by oasynnoum** [comment]
Thanks.
This extension does not support Windows currently, And I can't spend time for that. But I think I want to implement that in the future...

**Comment by oasynnoum** [comment]
Files for compilation on Windows like usb.dsp have generated with pecl-gen. So these files make no scence currently.
